
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
import Footer from "@/components/Footer";

const Affiliate = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <div className="flex-1 container mx-auto px-4 py-12">
        <div className="max-w-4xl mx-auto">
          {/* Logo at the top */}
          <div className="text-center mb-8">
            <img 
              src="/lovable-uploads/ed9037d0-d55e-4bd5-b525-febf2587d57b.png" 
              alt="FkiTT Logo" 
              className="h-16 md:h-20 mx-auto" 
            />
          </div>
          
          <div className="glass-card p-6 md:p-8 rounded-lg space-y-6 text-white">
            {/* Title */}
            <h1 className="text-4xl md:text-5xl font-bold text-center mb-4 text-white">
              Become a FkiTT Affiliate and Start Earning for Life
            </h1>
            
            <p className="text-lg">
              Ready to turn your audience into lifetime earnings? Join the FkiTT Affiliate Program and earn real, recurring income—without limits.
            </p>
            
            <div className="space-y-6">
              <h2 className="text-2xl md:text-3xl font-bold text-[#f9166f] mt-6">Affiliate Benefits:</h2>
              
              <ul className="space-y-4 list-disc pl-6">
                <li className="text-lg">
                  Earn 5% of all revenue paid by every member you refer.
                </li>
                
                <li className="text-lg">
                  Earn 5% of all revenue generated by every creator you refer.
                </li>
                
                <li className="text-lg">
                  No caps, no time limits – get paid for the lifetime of the member or creator.
                </li>
                
                <li className="text-lg">
                  Weekly payouts directly to your wallet.
                </li>
                
                <li className="text-lg">
                  No approval process or requirements to get started.
                </li>
                
                <li className="text-lg">
                  Full access to your own dashboard to track clicks, signups, and commissions.
                </li>
              </ul>
              
              <p className="text-lg">
                Whether you're a content creator, promoter, or just someone with a network, you can earn with FkiTT—starting Day 1.
              </p>
              
              <p className="text-lg">
                Signups open April 28th. Be one of the first affiliates and ride the wave early.
              </p>
              
              <p className="text-xl font-bold text-center text-[#f9166f] mt-6">
                Start earning with FkiTT. No limits. No filters. Just freedom.
              </p>
            </div>
            
            <div className="text-center pt-8">
              <Link to="/member-area">
                <Button size="lg" className="bg-[#f9166f] hover:bg-[#f9166f]/80 text-white font-bold py-3 px-8 rounded-md">
                  GET STARTED
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default Affiliate;
